services:
  postgres:
    image: postgres:17-alpine
    container_name: lab-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billingdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d billingdb"]
      interval: 5s
      timeout: 5s
      retries: 5
